apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-make
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-make@sha256:e223fd3c0b275b57ada75e017d12d2b7db2010d217ab3cb071d63b8cf30f398c
        name: my-nodejs
        resources: {}
status: {}
